name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kieabdocker.azurecr.io/demo/tetris-web
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: kieabdocker.azurecr.io
        username: admin
        password: ${{ secrets.DOCKERREGISTRYPASSWORD }}
    - name: Push to registry
      run: docker push kieabdocker.azurecr.io/demo/tetris-web
